version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Greet
          command: echo "Hello, World!"

workflows:
  version: 2
  build_and_greet:
    jobs:
      - build
